---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: get-rates-coinbase
  namespace: cce
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
          - name: get-rates-coinbase
            image: quay.io/cceshop/batcher-rates-coinbase:0.0.7
          restartPolicy: OnFailure
